//! Mirrors `net.h4bbo.lisbon.game.item.base.ItemBehaviour`.

#[derive(Clone, Copy, PartialEq, Eq, Debug, serde::Serialize)]
pub enum ItemBehaviour {
    Solid,
    CanStackOnTop,
    CanSitOnTop,
    CanStandOnTop,
    CanLayOnTop,
    CustomDataNumericOnOff,
    RequiresTouchingForInteraction,
    CustomDataTrueFalse,
    PublicSpaceObject,
    ExtraParameter,
    Dice,
    CustomDataOnOff,
    CustomDataNumericState,
    Teleporter,
    RequiresRightsForInteraction,
    Gate,
    PrizeTrophy,
    Roller,
    Redeemable,
    SoundMachine,
    SoundMachineSampleSet,
    Jukebox,
    WallItem,
    PostIt,
    Decoration,
    WheelOfFortune,
    RoomDimmer,
    Present,
    Photo,
    PlaceRollerOnTop,
    Invisible,
    Effect,
    RedirectRotation0,
    RedirectRotation2,
    SongDisk,
    RedirectRotation4,
    PetWaterBowl,
    PetFood,
    PetCatFood,
    PetDogFood,
    PetCrocFood,
    PetToy,
    PrivateFurniture,
}

impl ItemBehaviour {
    /// Mirrors `ItemBehaviour.valueOf` (case-insensitive here; Java callers
    /// upper-case the input first).
    pub fn from_str(name: &str) -> Option<Self> {
        match name.to_uppercase().as_str() {
            "SOLID" => Some(Self::Solid),
            "CAN_STACK_ON_TOP" => Some(Self::CanStackOnTop),
            "CAN_SIT_ON_TOP" => Some(Self::CanSitOnTop),
            "CAN_STAND_ON_TOP" => Some(Self::CanStandOnTop),
            "CAN_LAY_ON_TOP" => Some(Self::CanLayOnTop),
            "CUSTOM_DATA_NUMERIC_ON_OFF" => Some(Self::CustomDataNumericOnOff),
            "REQUIRES_TOUCHING_FOR_INTERACTION" => Some(Self::RequiresTouchingForInteraction),
            "CUSTOM_DATA_TRUE_FALSE" => Some(Self::CustomDataTrueFalse),
            "PUBLIC_SPACE_OBJECT" => Some(Self::PublicSpaceObject),
            "EXTRA_PARAMETER" => Some(Self::ExtraParameter),
            "DICE" => Some(Self::Dice),
            "CUSTOM_DATA_ON_OFF" => Some(Self::CustomDataOnOff),
            "CUSTOM_DATA_NUMERIC_STATE" => Some(Self::CustomDataNumericState),
            "TELEPORTER" => Some(Self::Teleporter),
            "REQUIRES_RIGHTS_FOR_INTERACTION" => Some(Self::RequiresRightsForInteraction),
            "GATE" => Some(Self::Gate),
            "PRIZE_TROPHY" => Some(Self::PrizeTrophy),
            "ROLLER" => Some(Self::Roller),
            "REDEEMABLE" => Some(Self::Redeemable),
            "SOUND_MACHINE" => Some(Self::SoundMachine),
            "SOUND_MACHINE_SAMPLE_SET" => Some(Self::SoundMachineSampleSet),
            "JUKEBOX" => Some(Self::Jukebox),
            "WALL_ITEM" => Some(Self::WallItem),
            "POST_IT" => Some(Self::PostIt),
            "DECORATION" => Some(Self::Decoration),
            "WHEEL_OF_FORTUNE" => Some(Self::WheelOfFortune),
            "ROOMDIMMER" => Some(Self::RoomDimmer),
            "PRESENT" => Some(Self::Present),
            "PHOTO" => Some(Self::Photo),
            "PLACE_ROLLER_ON_TOP" => Some(Self::PlaceRollerOnTop),
            "INVISIBLE" => Some(Self::Invisible),
            "EFFECT" => Some(Self::Effect),
            "REDIRECT_ROTATION_0" => Some(Self::RedirectRotation0),
            "REDIRECT_ROTATION_2" => Some(Self::RedirectRotation2),
            "SONG_DISK" => Some(Self::SongDisk),
            "REDIRECT_ROTATION_4" => Some(Self::RedirectRotation4),
            "PET_WATER_BOWL" => Some(Self::PetWaterBowl),
            "PET_FOOD" => Some(Self::PetFood),
            "PET_CAT_FOOD" => Some(Self::PetCatFood),
            "PET_DOG_FOOD" => Some(Self::PetDogFood),
            "PET_CROC_FOOD" => Some(Self::PetCrocFood),
            "PET_TOY" => Some(Self::PetToy),
            "PRIVATE_FURNITURE" => Some(Self::PrivateFurniture),
            _ => None,
        }
    }
}
